### PR TITLE
Boost sortuniq

### PR DESCRIPTION
**Pull request by tontonsb**
I noticed that my previous benchmarks were a bit optimistic as `fish` (just like `sh` and `zsh`) didn't take echoing into account. The actual times were a bit worse than normal sorts as `sortuniq` spent at least as much time echoing as it needs for sorting.

I tried out various ways like concatenating output in a string before echoing etc. The fastest solution that I found is what I propose in this PR. I will refer to it as `sortuniq2` in this post.

I set up a big random file and also filtered an ascii version.

```
dd if=/dev/urandom of=random_sortable bs=1M count=100 >/dev/null 2>&1
cat random_sortable | tr -dc "\n[:print:]" > ascii_sortable
```

Here are approximate benchmarks for filtering and echoing (I just wrapped the corresponding part of PHP in `$start = microtime(true);` and `$t = microtime(true)-$start; fwrite(STDERR, $time);` and ran it a couple of times).

action | sortuniq random | sortuniq ascii | sortuniq2 random | sortuniq2 ascii
-------|--------------|----------|--------|-----------
filtering | 0.50s | 0.35s | 0.50s | 0.35s
echoing to /dev/null | 0.92s | 0.88s | 0.20s | 0.10s
echoing to file | 2.6s | 2.45s | 0.48s | 0.19s
echoing to /dev/null with -c | 0.93s | 0.90s | 0.40s | 0.20s
echoing to file with -c | 2.65s | 2.50s | 0.67s | 0.28s

I was able to optimize the branch without `-c` a bit more.

I also benchmarked the total time of doing the duplicate deleting in various ways

command                  | random > sorted | ascii > sorted | random > null | ascii > null
-------------------------|-----------------|----------------|---------------|-------------
sort -u sortable  > out | 2.237 | 0.862 | 1.423 | 0.511
sort sortable \| uniq > out | 2.321 | 0.848 | 1.467 | 0.540
sort sortable \| uniq -c > out | 2.445 | 0.933 | 1.502 | 0.593
awk '!x[$0]++;' sortable  > out | 2.416 | 1.301 | 1.522 | 0.915
cat sortable \| sort -u > out | 4.868 | 1.771 | 3.963 | 1.488
cat sortable \| sort \| uniq > out | 4.326 | 1.613 | 3.605 | 1.349
cat sortable \| sort \| uniq -c > out | 4.376 | 1.689 | 3.715 | 1.437
cat sortable \| awk '!x[$0]++;' > out | 2.343 | 1.192 | 1.413 | 0.788
cat sortable \| ./sortuniq > out | 3.283 | 2.883 | 1.486 | 1.285
cat sortable \| ./sortuniq -c > out | 3.233 | 2.957 | 1.524 | 1.281
cat sortable \| ./sortuniq2 > out | 1.062 | 0.583 | 0.789 | 0.485
cat sortable \| ./sortuniq2 -c > out | 1.283 | 0.676 | 1.005 | 0.611

This is the code that I made the above table with:

```
dd if=/dev/urandom of=random_sortable bs=1M count=100 >/dev/null 2>&1
cat random_sortable | tr -dc "\n[:print:]" > ascii_sortable

measure() {
        command="$1 $2 $3 > $4"
        time=$(eval "{ time $command; } 2>&1" | awk -F'[sm]' '/real/{print $2}')
        printf "| $time "
}

testcommand() {
        printf "$1 sortable $2 > out "
        measure "$1" "random_sortable" "$2" "sorted"
        measure "$1" "ascii_sortable" "$2" "sorted"
        measure "$1" "random_sortable" "$2" "/dev/null"
        measure "$1" "ascii_sortable" "$2" "/dev/null"
        printf "\n"
}

printf "command                  | random > sorted | ascii > sorted | random > null | ascii > null\n"
print  "-------------------------|-----------------|----------------|---------------|-------------\n"

testcommand "sort -u" ""
testcommand "sort" "| uniq"
testcommand "sort" "| uniq -c"
testcommand "awk '!x[\$0]++;'" ""
testcommand "cat" "| sort -u"
testcommand "cat" "| sort | uniq"
testcommand "cat" "| sort | uniq -c"
testcommand "cat" "| awk '!x[\$0]++;'"
testcommand "cat" "| ./sortuniq"
testcommand "cat" "| ./sortuniq -c"
testcommand "cat" "| ./sortuniq2"
testcommand "cat" "| ./sortuniq2 -c"

rm random_sortable
rm ascii_sortable
rm sorted
```

### CODE REVIEW

**Comment by 0ki** [comment]
I wrote this tool to help me with ~1GB text files that have some lines in common and ~300GB text files that have almost all lines in common. (Let's call them "realistic cases").

Try doing some speed comparison on realistic cases, I'm thinking that time savings will not be as noticeable. Your proposal seems to require disproportionate time-space trade-off. Memory usage will jump 200% (or maybe, 300%; haven't measured it yet).

**Comment by tontonsb** [comment]
Alright, I'll try to take a look, probably only next weekend though.

For additional excitement I will throw out my bet that the memory usage filtering my files will increase to something like 120% of original and remain below 200% for all cases, approaching it as the average line length increases.

**Comment by tontonsb** [comment]
# Realistic cases?

By making the random file 10 times larger I got 1GB of crap data and filtered it to 400MB of ascii data. Either way it has 4'096'304 lines. The random file had 4'062'829 unique lines, the ascii one - 3'977'565 unique lines. So I'd say these could count as the "~1GB with few duplicates" case.

I have also added a `sortuniq3` where I concatenate the string manually (pretty much `sortuniq` with `$out .= ` instead of `echo`) and echo at the end.

The speed results showed pretty much the same picture

command                  | random > sorted | ascii > sorted | random > null | ascii > null
-------------------------|-----------------|----------------|---------|------------
sort -u sortable  > out | 24.979 | 9.145 | 13.678 | 5.830
cat sortable | ./sortuniq > out | 32.737 | 28.454 | 15.218 | 13.687
cat sortable | ./sortuniq -c > out | 34.018 | 29.635 | 15.707 | 13.306
cat sortable | ./sortuniq2 > out | 11.587 | 6.215 | 7.929 | 4.877
cat sortable | ./sortuniq2 -c > out | 13.908 | 7.767 | 10.468 | 6.133
cat sortable | ./sortuniq3 > out | 15.027 | 7.108 | 11.611 | 6.043
cat sortable | ./sortuniq3 -c > out | 15.443 | 7.887 | 11.997 | 6.532

Memory usage (doesn't matter where the output is)

command                  | random | ascii 
-------------------------|-----------------|----------------
sortuniq | 1'409'426'576 | 688'881'224
sortuniq -c | 1'409'430'416 | 688'882'568
sortuniq2 | 2'657'183'304 | 1'279'709'248
sortuniq2 -c |  3'895'491'528 | 1'795'094'376
sortuniq3 | 2'457'953'240 | 1'081'843'152
sortuniq3 -c | 2'466'076'208 | 1'089'801'896

So not great indeed. My first attempt bloats to 180-190% without `-c` and 260-280% with it. The new `sortuniq3` only added the size of the output to the memory usage, but that's still pretty bad.

**Comment by tontonsb** [comment]
# However

In the examples above you can see how much faster is dumping to `/dev/null` than writing to file. The actual filtering took only around 5.2s for the junk file and 3.4s for ascii-only file. So output doubles execution time even for my best attempt and 6-8x in the original. While echo is really slow, concatenations turn out quite slow as well as they build up... 

A solution for that turns out to be output buffering. I tried both the native `ob_` as well as manually echoing concatenated `$out` when it exceeds certain length. The performance in speed and memory was the same, so I went with the native.

By empirical poking I found that buffer sizes up to 100K measurably improve speed (compared to 10K or smaller), but after that (trying 1M or 500K) the speedup is on par with random fluctuations, so I ended up choosing 100K buffer.

Here are my final results, where `sortuniq` is the original and `sortuniq_` is the one that I offer right now in this PR.

command | random > sorted | ascii > sorted | random > null | ascii > null | random, mem | ascii, mem
-------------|--|--|--|--|--|--
sortuniq      | 32.487 | 28.969 | 14.389 | 12.120 | 1'409'426'576 | 688'881'224
sortuniq -c  | 32.331 | 28.824 | 14.768 | 13.001 | 1'409'430'416 | 688'882'568
sortuniq_     | 8.024 | 4.251 | 6.191 | 4.173 | 1'409'529'320 | 688'984'032
sortuniq_ -c | 8.538 | 4.479 | 6.612 | 4.578 | 1'409'533'408 | 688'985'560

That's just 100K memory overhead.

**Comment by 0ki** [comment]
Thank you for the extensive testing. I can confirm that this version is better for both"~1GB text files that have some lines in common" and "~300GB text files that have almost all lines in common". Thanks!

**Pull request merged**
